

spline:
	g++ splineinterp.cpp -o interp.a -lgsl
	./interp.a > plot.dat
	graph -T X -L "spline Interpolation" < plot.dat 

linear:
	g++ lininterp.cpp -o interp.a -lgsl
	./interp.a > plot.dat
	graph -T X  -L "linear Interpolation"< plot.dat






